import config from '../../config';

export default styles = {
  Map: {
    flex: 1,
  },
  MapView: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  MyMarkerContainer: {
    width: 30,
    height: 30,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  MyMarker1: {
    width: 28,
    height: 28,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: 'white',
    backgroundColor: config.colorMain,
    justifyContent: 'center',
    alignItems: 'center',
  },
  MyMarker2: {
    width: 12,
    height: 12,
    borderRadius: 12,
    backgroundColor: 'white',
  },
  UserMarkerContainer: {
    width: 20,
    height: 20,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  UserMarker: {
    width: 18,
    height: 18,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'white',
    backgroundColor: config.colorMain,
    justifyContent: 'center',
    alignItems: 'center',
  },
  SearchInputContainer: {
    position: 'absolute',
    top: 30,
    left: 20,
    right: 20,
    zIndex: 100,
  },
  Pulse: {
    position: 'absolute',
    width: 1,
    height: 1,
    top: '50%',
    left: '50%',
    backgroundColor: 'red',
    borderRadius: 100,
  },
  MapErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  MapError: {
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    fontSize: 16,
  },
  MemberInfo: {
    position: 'absolute',
    bottom: 20,
    zIndex: 20,
    backgroundColor: '#181820',
    left: 20,
    right: 20,
    padding: 20,
    borderRadius: 8,
  },
  MemberImage: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  MemberName: {
    fontFamily: 'Poppins-Regular',
    fontSize: 16,
  },
  MemberNameContainer: {
    paddingLeft: 20,
  },
  CarDetails: {
    flexDirection: 'row',
  },
  CarDetailsContainer: {
    paddingLeft: 20,
  },
  CarIcon: {
    height: 40,
    width: 40,
    opacity: 0.3,
  },
  CarMake: {
    textTransform: 'capitalize',
    fontFamily: 'Poppins-Medium',
  },
  CarModel: {
    textTransform: 'capitalize',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
  },
  ButtonContainer: {
    flexDirection: 'row',
    marginTop: 20,
  },
  CloseButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 30,
    height: 30,
  },
  CenterMap: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    zIndex: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    height: 40,
    width: 40,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
};
