export enum Screens {
  HOME = 'HOME',
  PROFILE = 'PROFILE',
  COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION',
  SETTINGS = 'SETTINGS',
  PRIVACY = 'PRIVACY',
  GET_HELP = 'GET_HELP',
  MY_EVENTS = 'MY_EVENTS',
  EDIT_PROFILE = 'EDIT_PROFILE',
  EVENTS_LIST = 'EVENTS_LIST',
  EVENT_DETAILS = 'EVENT_DETAILS',
}
