export enum Screens {
  HOME = 'HOME',
  // Profile
  PROFILE = 'PROFILE',
  SETTINGS = 'SETTINGS',
  PRIVACY = 'PRIVACY',
  GET_HELP = 'GET_HELP',
  MY_EVENTS = 'MY_EVENTS',
  EDIT_PROFILE = 'EDIT_PROFILE',

  // Events
  EVENTS_LIST = 'EVENTS_LIST',
  EVENT_DETAILS = 'EVENT_DETAILS',

  // Auth
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  FORGOTTEN_PASS = 'FORGOTTEN_PASS',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION',
}
